name: "FHIR Validation Markdown Renderer"
description: >
  Parses the JSON `OperationOutcome` bundle produced by the Java FHIR Validator, emits GitHub check annotations (❌, ⚠️, ℹ️) for issues at or above the configured severity, supports optional filtering by `messageId` and wildcard patterns on the details text, and generates a summary Markdown table with issue counts and columns (File, Severity, Details, Location, Code, MessageId) in the GitHub Checks UI.
author: "Patrick Werner <pa.f.werner@gmail.com>"
inputs:
  bundle-file:
    description: "Path to the OperationOutcome JSON file"
    required: false
    default: "validation.json"
  include:
    description: |
      Which severities to output:
      - errors: only issues with severity = error
      - warnings: issues with severity = error or warning
      - all: issues of any severity (error, warning, information)
    required: false
    default: "errors"
  filters:
    description: >
      Line-separated list of filters in the form
      `messageId|detailsWildcard`.
      - `messageId` must match exactly.
      - `detailsWildcard` may use `*` as a wildcard.
      - If one part is empty, it will be ignored.
    required: false

runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "terminal"
  color: "black"