name: Build and Commit dist

on:
  # Run on every push to any branch (or limit to e.g. 'main' if you prefer)
  push:
    branches:
      - '**'
  # Also run when a release is published
  release:
    types:
      - published
  # Allow manual invocation
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build with ncc
        run: npm run build

      - name: Commit built files and lockfile
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: 'chore: build dist and lockfile [skip ci]'
          add: |
            dist/
            package-lock.json
